name: Language Stats

on:
  push:
    branches:
      - main # or your default branch
  schedule:
    - cron: "0 0 * * *" # Runs every day

jobs:
  generate-languages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Language Chart
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_details: percentage, lines
          plugin_languages_threshold: 0%
