name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"  # Every day at midnight
  workflow_dispatch: # Allow manual updates

jobs:
  generate-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          user: JuiceJully  # Replace with your GitHub username
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_languages: yes
          plugin_languages_ignored: # Ignore languages if you want
          plugin_languages_limit: 6 # Limit number of languages
          # Set the output to a publicly accessible URL (hosted externally)
          output: https://raw.githubusercontent.com/juicejully/juicejully/gh-pages/github-metrics.svg  # External hosted URL

      - name: Commit metrics file to gh-pages branch (optional)
        run: |
          git config --global user.email "youremail@example.com"
          git config --global user.name "juicejully"
          git checkout -b gh-pages
          git add github-metrics.svg
          git commit -m "Add GitHub metrics image"
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token for committing to gh-pages
